//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Ksiazki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ksiazki()
        {
            this.Wypozyczenia = new ObservableCollection<Wypozyczenia>();
        }
    
        public int id_ksiazki { get; set; }
        public string ISBN { get; set; }
        public string Tytul { get; set; }
        public string Opis { get; set; }
        public Nullable<int> id_kategoria { get; set; }
        public Nullable<int> id_autor { get; set; }
        public Nullable<int> id_wydawnictwa { get; set; }
        public Nullable<int> Rok_Wydania { get; set; }
    
        public virtual Autorzy Autorzy { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        public virtual Wydawnictwa Wydawnictwa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
