//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Wypozyczenia
    {
        public int id_wypozyczenia { get; set; }
        public Nullable<int> id_czytelnik { get; set; }
        public Nullable<int> id_ksiazki { get; set; }
        public Nullable<System.DateTime> Data_wypozyczenia { get; set; }
        public Nullable<int> id_pracownik_wypozyczenie { get; set; }
        public Nullable<System.DateTime> Data_oddania { get; set; }
        public Nullable<int> id_pracownik_oddanie { get; set; }
    
        public virtual Czytelnicy Czytelnicy { get; set; }
        public virtual Ksiazki Ksiazki { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Pracownicy Pracownicy1 { get; set; }
    }
}
